// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdpi4WPSSd7Rwvez_Z51qzL7BmHpXjxk',
    appId: '1:481850791609:web:a072f9e88a4fbb89aaed68',
    messagingSenderId: '481850791609',
    projectId: 'my-notes-2b582',
    authDomain: 'my-notes-2b582.firebaseapp.com',
    storageBucket: 'my-notes-2b582.appspot.com',
    measurementId: 'G-09L393657J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdfl7Flpl-bFIGelVJL_HOMXUU4xJ9-b0',
    appId: '1:481850791609:android:95b15d13a838679aaaed68',
    messagingSenderId: '481850791609',
    projectId: 'my-notes-2b582',
    storageBucket: 'my-notes-2b582.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG-w2qcQUCBBNRAxW4HPTb66N63ibHpnY',
    appId: '1:481850791609:ios:4ea7d8041ca9011baaed68',
    messagingSenderId: '481850791609',
    projectId: 'my-notes-2b582',
    storageBucket: 'my-notes-2b582.appspot.com',
    iosBundleId: 'com.myfirst.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG-w2qcQUCBBNRAxW4HPTb66N63ibHpnY',
    appId: '1:481850791609:ios:4ea7d8041ca9011baaed68',
    messagingSenderId: '481850791609',
    projectId: 'my-notes-2b582',
    storageBucket: 'my-notes-2b582.appspot.com',
    iosBundleId: 'com.myfirst.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRdpi4WPSSd7Rwvez_Z51qzL7BmHpXjxk',
    appId: '1:481850791609:web:e4fb99f381a6cacbaaed68',
    messagingSenderId: '481850791609',
    projectId: 'my-notes-2b582',
    authDomain: 'my-notes-2b582.firebaseapp.com',
    storageBucket: 'my-notes-2b582.appspot.com',
    measurementId: 'G-JT4E66WB39',
  );
}
